language: java
jdk:
  - oraclejdk11
  - openjdk10
  - openjdk11
#for caching in travis.yml file
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
deploy:
  # deploy develop to the staging environment
  - provider: script
    script: bash scripts/deploy.sh staging
    on:
      branch: dev
  # deploy master to production
  - provider: script
    script: bash scripts/deploy.sh production
    on:
      branch: master